### ISSUE TITLE
When we remove itens from the classification plan, if they have subitens in a collapsed mode (e.g. folders) these stay as ghosts forever in the app

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#216]

**Comment by sleroux-keep** [comment]
Fixed @ 5a9a7a127eb4ee147055a52be5340ed2236d91d8

**Comment by jmaferreira** [comment]
Not fixed yet on version alpha10.

**Comment by jmaferreira** [comment]
Its still not perfect. It doesn't work well with hidden files, but its better.
